### PR TITLE
Prettier configuration

### PR DESCRIPTION
**Pull request by lizbanach**
- installs [prettier](https://prettier.io/)
- adds a pre-commit hook to format files using [pretty quick](https://github.com/azz/pretty-quick)
- formats all files

### CODE REVIEW

**Comment by izgeorge** [comment]
Is there any way we can choose not to format all of these files? I'm worried this will cause an unsightly amount of conflicts for devs that are continuing to work while we update UI styles.

**Comment by izgeorge** [comment]
oh i just saw the last commit. yeah i would remove that for now

**Comment by lizbanach** [comment]
@izgeorge good point!

**Comment by newhouseb** [comment]
this is awesome!

**Pull request merged**
